Reasons update
fondberg/easee_hass pull request #185
Opened 2022-05-17 21:50 UTC by olalid

The "reason for no current" sensor has new values that needs to be incorporated.
Translations should be added before release.

2022-05-17 21:51 UTC, olalid commented
@tmjo Can you look at the Norwegian translations please?

2022-05-17 21:53 UTC, olalid commented
@tobiasbayer Would you be able to do the new german translations please?

2022-05-18 06:18 UTC, tobiasbayer commented
Sure: https://github.com/fondberg/easee_hass/pull/187

2022-05-18 10:10 UTC, tmjo commented
> @tmjo Can you look at the Norwegian translations please?

Ok, done!

2022-05-19 06:36 UTC, astrandb requested changes

2022-05-19 06:36 UTC, astrandb commented on custom_components/easee/translations/sensor.sv.json
>        "limited_by_circuit_max_limit": "Begärnsad av max krets-gräns",
```suggestion
      "limited_by_circuit_max_limit": "Begränsad av max krets-gräns",
```

2022-05-19 06:36 UTC, astrandb commented on custom_components/easee/translations/sensor.sv.json
>        "limited_by_circuit_max_limit": "Begärnsad av max krets-gräns",
Spelling error

2022-05-19 07:14 UTC, astrandb approved these changes

2022-05-19 18:15 UTC, merged