add temperature reading
fondberg/easee_hass pull request #266
Opened 2023-01-21 20:05 UTC by zeeZ

These are the bits I added locally to get a temperature reading:
![image](https://user-images.githubusercontent.com/715896/213884827-047322a7-62cb-4215-b84d-e32251e80e9e.png)

Two points:
- I'm not very familiar with HA internals, so I don't know if the entity settings are correct.
- The controller would error due to the oldvalue key not existing until stream data arrives, so I made it an optional None with the `.get()` instead. I don't know of this how this affects the `lifetimeEnergy ` bit.

I do not know if this 100% works as is, especially on a fresh setup. Currently it's "works on my machine", but I might have time to actually test soonish.

2023-01-21 21:54 UTC, olalid commented
Thanks for contributing!

I have not tried it yet, but looks like a good approach.
I am thinking we should add also temperature sensor for equalizer (state_internalTemperature).
There also seems to be more details available that we can add later as attributes to the charer temperature sensor, but that requires changes in the lib first so we can wait with that until we have something more pressing to change in the lib.
(e.g. TempInputT2, TempOutputN etc).

2023-03-19 15:37 UTC, astrandb requested changes
Looks good to me.

2023-03-19 15:37 UTC, astrandb commented on custom_components/easee/const.py
> +    TEMP_CELSIUS,
```suggestion
    UnitOfTemperature,
```

2023-03-19 15:37 UTC, astrandb commented on custom_components/easee/const.py
> +        "units": TEMP_CELSIUS,
```suggestion
        "units": UnitOftemperature.CELSIUS,
```

2023-03-19 15:51 UTC, astrandb requested changes

2023-03-19 15:51 UTC, astrandb commented on custom_components/easee/const.py
> +        "icon": "mdi:temperature-celsius",
```suggestion
```
This icon is wrong if user changes the unit of measurement. Remove and let HA use standard icon based on device_class.

2023-03-20 18:16 UTC, zeeZ commented
I've added the units related changes (and totally didn't forget to lint).

On testing with a fresh empty instance, on startup it produces the following warning once per charger, and I'm not really sure what's happening there:

> WARNING (MainThread) [homeassistant.components.sensor] Sensor sensor.easee_home_xxxxxx_temp_max has device class temperature, state class measurement and unit °C thus indicating it has a numeric value; however, it has the non-numeric value:  (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

I don't see where it could be getting a string from, I'm expecting an int from pyeasee or a None.

2023-03-25 17:04 UTC, olalid commented
Perhaps it is somehow because no value is yet set when the sensor is first created/updated?

(It is most likely transferred as a double I would think, rather than int, but I guess that is what you meant).

2023-03-25 17:25 UTC, zeeZ commented
Yeah, no value exists at first and it is only created once the stream comes in, but the `str` still puzzles me.

> (It is most likely transferred as a double I would think, rather than int, but I guess that is what you meant).

The [documentation](https://developer.easee.cloud/docs/observation-ids) says it's a double, but it seems to actually be an integer:

`[custom_components.easee.controller] Callback EHXXXXXX 4 150 state_tempMax 21`

2023-03-29 10:33 UTC, olalid commented
We are going to move to a new way to retrieve the initial states of the chargers/equalizers soon, I think we can probably retrieve the initial state of this sensor too with that approach since we will be able to list exactly what data we we need.
So I would not spend too much effort on trying to solve that initial state problem right now.

2023-04-07 15:49 UTC, astrandb commented
This temperature sensor is included in PR #291

2023-04-09 10:38 UTC, closed without merging