More status codes
fondberg/easee_hass pull request #324
Opened 2023-05-06 09:18 UTC by StevoNL

Add new status codes, update missed sensor translation.

2023-05-06 09:30 UTC, olalid commented
Thanks @StevoNL. I literally just pressed the button on a new release so we just missed this, but whenever we feel we have a few things to correct we will include this.

2023-05-06 13:59 UTC, astrandb requested changes
Thank you for the contribution. 
Just a little comma missing,

2023-05-06 13:59 UTC, astrandb commented on custom_components/easee/translations/nl.json
>            "ready_to_charge": "Gereed om te laden"
```suggestion
          "ready_to_charge": "Gereed om te laden",
```
Missing comma

2023-05-07 06:41 UTC, astrandb approved these changes

2023-05-23 13:51 UTC, merged